
package view;

import database.Invoice;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public class Invoice_view extends javax.swing.JFrame {

    private Invoice inv;
    private int invID;

    public Invoice_view(int invID) {
        inv = new Invoice();
        this.invID = invID;
        
        inv.connect();
        initComponents();        
        addInfo();
        addProducts();
        summary();
        inv.disconnect();
    }

    private void addInfo() {
        inv.setInvoiceID(invID);

        cusid.setText(inv.getCustomerID());
        cusName.setText(inv.getCustomerName());
        companyName.setText(inv.getCompanyName());
        invoiceID.setText(invID + "");
        soID.setText(inv.getSOID() + "");
        date.setText(inv.getDateInvoice());
        approveID.setText(inv.getApproveID() + "");
        dateApprove.setText(inv.getDateApprove());
    }

    private void addProducts() {
        ArrayList<HashMap> products = inv.getProducts();
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        int line = 0;
        for (HashMap product : products) {
            model.addRow(new Object[0]);
            model.setValueAt(line+1, line, 0);
            //model.setValueAt(product.get("PRODUCTID"), line, 1); // just for test
            model.setValueAt(product.get("PRODUCTID"), line, 1);
            model.setValueAt(product.get("PRODUCTNAME"), line, 2);
            model.setValueAt(product.get("AMOUNT"), line, 3);
            model.setValueAt(product.get("TYPEOFPRODUCT"), line, 4);
            model.setValueAt(String.format("%,.2f", product.get("PRICE")), line, 5);
            model.setValueAt(String.format("%,.2f", product.get("TOTALPRICE")), line, 6);
            line++;
        }
    }
    
    private void summary() {
        Double sumTotalPrice = inv.getSumTotalPrice();
        Double discount = inv.getDiscount();
        Double price = sumTotalPrice - discount;
        
        totalPrice.setText(String.format("%,.2f", sumTotalPrice));
        totalDiscount.setText(String.format("%,.2f", discount));
        finalPrice.setText(String.format("%,.2f", price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        totalDiscount = new javax.swing.JLabel();
        finalPrice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        invoiceID = new javax.swing.JLabel();
        companyName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        soID = new javax.swing.JLabel();
        cusid = new javax.swing.JLabel();
        cusName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        approveID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dateApprove = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jButton2.setText("เสร็จสิ้น");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, 25));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel6.setText("จำนวนเงินทั้งหมด");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel7.setText("จำนวนเงินรวม");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel8.setText("ส่วนลดการค้า");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        totalPrice.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalPrice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 110, 25));

        totalDiscount.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        totalDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDiscount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        totalDiscount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(totalDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, 25));

        finalPrice.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        finalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finalPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        finalPrice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(finalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 110, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 700, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, 20));

        jLabel13.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel13.setText("วันที่ใบส่งของ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        invoiceID.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(invoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 100, 20));

        companyName.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 120, 20));

        jLabel12.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel12.setText("ชื่อบริษัท");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel1.setText("อ้างถึง SO No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel3.setText("ชื่อผู้ติดต่อ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, -1));

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel5.setText("เลขที่ใบส่งของ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel11.setText("รหัสลูกค้า");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        soID.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(soID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 100, 20));

        cusid.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 12, 140, 20));

        cusName.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, 20));

        jLabel17.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 20));

        jLabel14.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel14.setText("เลขที่ใบกำกับ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        approveID.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(approveID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 100, 20));

        jLabel15.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel15.setText("วันที่ใบกำกับ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        dateApprove.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(dateApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 110, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 110));

        productTable.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "รหัสสินค้า", "ชื่อสินค้า", "จำนวน", "หน่วย", "ราคา/หน่วย", "จำนวนเงิน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setRowHeight(20);
        jScrollPane3.setViewportView(productTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 700, 190));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Invoice");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/vicspeedBG.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/vicspeedBG.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approveID;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel cusName;
    private javax.swing.JLabel cusid;
    private javax.swing.JLabel date;
    private javax.swing.JLabel dateApprove;
    private javax.swing.JLabel finalPrice;
    private javax.swing.JLabel invoiceID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel soID;
    private javax.swing.JLabel totalDiscount;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
