/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import database.ListSo;
import java.awt.BorderLayout;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.DimensionUIResource;

/**
 *
 * @author eawarnong
 */
public class ListSO_view extends javax.swing.JFrame {

    /**
     * Creates new form ListSO_view
     */
    ListSo list;
    
    public ListSO_view() {
        //list = new ListSo();
        
        initComponents();
        //mainPanel.setBackground(Color.RED);
        //mainPanel.setBackground(Color.BLUE);
        //addListSOs(list.getProblemSoIDs(), Color.RED);
        //addListSOs(list.getNormalSoIDs(), Color.WHITE);
        addListSOs();
    }

    public void addListSOs(/*ArrayList<HashMap> lists, Color color*/) {
        //for(HashMap list : lists) {
        for(int i = 0; i < 15; i++) {
            JPanel pnlLine = new JPanel();
            JPanel pnlButton = new JPanel();
            JLabel lbl = new JLabel();
            
            // set proporty of pnlLine
            pnlLine.setLayout(new BorderLayout());
            pnlLine.setBorder(new javax.swing.border.LineBorder(Color.BLACK, 1, false));
            pnlLine.setMinimumSize(new Dimension(mainPanel.getWidth() - 15, 40));
            pnlLine.setPreferredSize(new Dimension(mainPanel.getWidth() - 15, 40));
            pnlLine.setMaximumSize(new Dimension(mainPanel.getWidth() - 15, 40));
            //pnlLine.setBackground(color);
            
            //lbl.setText(String.valueOf(list.get("SOID")));
            //lbl.setFont(new java.awt.Font("Angsana New", 0, 20));
            lbl.setText("555555555");
            lbl.setFont(new java.awt.Font("Angsana New", 0, 20));
            lbl.setBorder(new EmptyBorder(0, 5, 0, 0));
            pnlLine.add(lbl, BorderLayout.WEST);
            
            pnlButton.setLayout(new BorderLayout());
            pnlButton.add(new SOButton());
            pnlLine.add(pnlButton, BorderLayout.EAST);
            
            mainPanel.add(pnlLine);
        }
    }
    
    class SOButton extends JButton {
        
        public SOButton() {
            init();
        }
        
        public void init() {
            addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    new SaleOrder_view().setVisible(true);
                }
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox = new javax.swing.JComboBox();
        jTextField = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPanel = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "เลขที่ใบสั่งขาย", "วันที่เอกสารใบสั่งขาย", "รหัสลูกค้า", "ชื่อลูกค้า", "ชื่อบริษัท" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        jTextField.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 200, 30));

        jBtnSearch.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jBtnSearch.setText("ค้นหา");
        jPanel1.add(jBtnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 60));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("List Sale Order");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPanel.setViewportView(mainPanel);

        getContentPane().add(jScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 700, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/vicspeedBG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSO_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSO_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSO_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSO_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSO_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTextField jTextField;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
