package view;

import database.Invoice;
import database.SaleOrder;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class Refund_view extends javax.swing.JFrame {

    /**
     * Creates new form Refund_view
     */
    private int soid;
    private DefaultTableModel model;
    private SaleOrder so;

    public Refund_view(int soid) {
        this.soid = soid;

        initComponents();
        resizeTable(soTable);
        resizeTable(invoiceTable);
        so = new SaleOrder();

        so.connect();

        addInfo();
        soTable();
        invoiceTable();
        refundReport();

        so.disconnect();
        //super.setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalSO = new javax.swing.JLabel();
        totalInvoice = new javax.swing.JLabel();
        refund = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SOid = new javax.swing.JLabel();
        companyName = new javax.swing.JLabel();
        customerID = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        invCombo = new javax.swing.JComboBox();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        soTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Invoice.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SO.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 90, 30));

        jButton2.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jButton2.setText("เสร็จสิ้น");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, 25));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel6.setText("ส่วนลดการค้าที่เรียกคืน");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel7.setText("จำนวนเงินรวมในใบสั่งขาย");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel8.setText("จำนวนเงินรวมในใบกำกับ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        totalSO.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        totalSO.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalSO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(totalSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 25));

        totalInvoice.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        totalInvoice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalInvoice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(totalInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 90, 25));

        refund.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        refund.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        refund.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(refund, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 90, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 700, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel1.setText("อ้างถึง SO No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel3.setText("ชื่อผู้ติดต่อ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel5.setText("เลขที่ใบกำกับ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel4.setText("ชื่อบริษัท");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jLabel11.setText("รหัสลูกค้า");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        SOid.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(SOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, 20));

        companyName.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 110, 20));

        customerID.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        customerID.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                customerIDComponentShown(evt);
            }
        });
        jPanel1.add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 20));

        customerName.setFont(new java.awt.Font("Angsana New", 1, 20)); // NOI18N
        jPanel1.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, 20));

        jLabel17.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 20));

        jPanel1.add(invCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 90, -1));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/searchButton.png"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 700, 80));

        soTable.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        soTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " No.", "รหัสสินค้า", "ชื่อสินค้า", "จำนวน", "หน่วย", "ราคา/หน่วย", "จำนวนเงิน"
            }
        ));
        soTable.setRowHeight(20);
        jScrollPane1.setViewportView(soTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 700, 90));

        invoiceTable.setFont(new java.awt.Font("Angsana New", 0, 20)); // NOI18N
        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "รหัสสินค้า", "ชื่อสินค้า", "จำนวน", "หน่วย", "ราคา/หน่วย", "จำนวนเงิน"
            }
        ));
        invoiceTable.setRowHeight(20);
        jScrollPane3.setViewportView(invoiceTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 700, 90));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Refund");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/vicspeedBG.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIDComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_customerIDComponentShown
        // TODO add your handling code here:
        //customerID.setText("text");
    }//GEN-LAST:event_customerIDComponentShown

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        so.connect();

        int invID = Integer.parseInt(String.valueOf(invCombo.getSelectedItem()));
        Invoice_view invoiceView = new Invoice_view(invID);
        invoiceView.setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        invoiceView.setLocation(screenSize.width / 3 + 50, screenSize.height / 4 + 50);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                invoiceView.dispose();
            }
        });

        so.disconnect();
    }//GEN-LAST:event_searchBtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void addInfo() {

        so.setSoID(soid);

        customerID.setText(so.getCustomerID() + "");
        customerName.setText(so.getCustomerName());
        SOid.setText(soid + "");
        companyName.setText(so.getCustomerCompany());

        ArrayList<HashMap> invIDs = so.getInvoiceIDs();
        for (HashMap invID : invIDs) {
            invCombo.addItem(invID.get("INVOICEID"));
        }

    }
    
    private void resizeTable(JTable table) {
        table.getColumnModel().getColumn(0).setPreferredWidth(10);
        table.getColumnModel().getColumn(1).setPreferredWidth(75);
        table.getColumnModel().getColumn(2).setPreferredWidth(140);
        table.getColumnModel().getColumn(3).setPreferredWidth(60);
        table.getColumnModel().getColumn(4).setPreferredWidth(60);
        table.getColumnModel().getColumn(5).setPreferredWidth(90);
        table.getColumnModel().getColumn(6).setPreferredWidth(90);
    }

    public void soTable() {
        ArrayList<HashMap> products = so.getProducts();
        DefaultTableModel model = (DefaultTableModel) soTable.getModel();
        int line = 0;
        for (HashMap product : products) {
            model.addRow(new Object[0]);
            model.setValueAt(line + 1, line, 0);
            model.setValueAt(product.get("PRODUCTID"), line, 1);
            model.setValueAt(product.get("PRODUCTNAME"), line, 2);
            model.setValueAt(product.get("AMOUNT"), line, 3);
            model.setValueAt(product.get("TYPEOFPRODUCT"), line, 4);
            model.setValueAt(String.format("%,.2f", product.get("PRICE")), line, 5);
            model.setValueAt(String.format("%,.2f", product.get("TOTALPRICE")), line, 6);
            line++;
        }
    }

    public void invoiceTable() {
        ArrayList<HashMap> products = so.getAllInvioceProducts();
        DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
        int line = 0;
        for (HashMap product : products) {
            model.addRow(new Object[0]);
            model.setValueAt(line + 1, line, 0);
            model.setValueAt(product.get("PRODUCTID"), line, 1);
            model.setValueAt(product.get("PRODUCTNAME"), line, 2);
            model.setValueAt(product.get("AMOUNT"), line, 3);
            model.setValueAt(product.get("TYPEOFPRODUCT"), line, 4);
            model.setValueAt(String.format("%,.2f", product.get("PRICE")), line, 5);
            model.setValueAt(String.format("%,.2f", product.get("TOTALPRICE")), line, 6);
            line++;
        }
    }

    public void refundReport() {
        double totalInvInfo = (100 - so.getDiscount()) * so.getSumTotalPriceInvoice() / 100;
        totalSO.setText(String.format("%,.2f", so.getTotalSO()));
        totalInvoice.setText(String.format("%,.2f", totalInvInfo));
        refund.setText(String.format("%,.2f", so.getSumDiscount()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SOid;
    private javax.swing.JLabel companyName;
    private javax.swing.JLabel customerID;
    private javax.swing.JLabel customerName;
    private javax.swing.JComboBox invCombo;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel refund;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable soTable;
    private javax.swing.JLabel totalInvoice;
    private javax.swing.JLabel totalSO;
    // End of variables declaration//GEN-END:variables
}
